package com.example.movies.presentation

object TestTags {
    const val MOVIE_DETAILS_SCREEN = "MOVIE_DETAILS_SCREEN"
    const val MOVIE_DETAILS_POSTER_IMAGE = "MOVIE_DETAILS_POSTER_IMAGE"
    const val MOVIE_DETAILS_TITLE = "MOVIE_DETAILS_TITLE"
    const val MOVIE_DETAILS_RELEASE_DATE = "MOVIE_DETAILS_RELEASE_DATE"
    const val MOVIE_DETAILS_RATING = "MOVIE_DETAILS_RATING"
    const val MOVIE_DETAILS_OVERVIEW = "MOVIE_DETAILS_OVERVIEW"
}