name: Autogenerate Hotfix PRs

on:
  create:
    branches:
      - 'hotfix/*'
      - 'release/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set PR Targets
        id: targets
        run: |
          # Initialize targets variable
          targets="main dev"
          
          # Determine additional targets based on branch name
          if [[ "${GITHUB_REF#refs/heads/}" == hotfix/* ]]; then
            echo "label=hotfix" >> $GITHUB_ENV
            # Find all release/* branches and add them to targets
            release_branches=$(git branch -r | grep 'origin/release/' | sed 's|origin/||')
            for branch in $release_branches; do
              targets="$targets $branch"
            done
          elif [[ "${GITHUB_REF#refs/heads/}" == release/* ]]; then
            echo "label=hotfix" >> $GITHUB_ENV
          fi

          # Export targets as environment variable
          echo "targets=$targets" >> $GITHUB_ENV

      - name: Create Pull Requests
        run: |
          for target in ${{ env.targets }}; do
            gh pr create --title "PR: Merge ${{ github.ref_name }} into ${target}" \
                         --body "Automatically generated PR for branch ${{ github.ref_name }} to ${target}." \
                         --base ${target} \
                         --head ${{ github.ref_name }} \
                         --label ${{ env.label }} \
                         --draft
          done
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
